package com.im.trainings.java.model;


import lombok.Data;

@Data
public class Customer implements Comparable {

    // Setters and Getters are automatically generated by lombok.
    private int id;
    private String name;


    @Override
    public int compareTo(Object o) {
        return Integer.compare(this.id, ((Customer) o).id);
    }
}
